name: fixandchangenameUI
main: rr\Main
version: 1.0.1
api: 3.0.0
author: bumbumkill
depend:
 - EconomyAPI
 - FormAPI

commands:
 fixandchangenameui:
  aliases: [facnui]
  description: "§o§bEnter §7FixAndChangeNameUI"
  permission: facnui.cmd.use
